### ISSUE TITLE
Crash at 16 GiB into the file

### ISSUE THREAD

**Issue by schneider42** [miek/inspectrum#37]
I've just tried to work with a roughly 40 GiB large file at 2 Msps.

At roughly 1073 seconds into the file inspectrum crashes with the following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x000000000040eab6 in InputSource::getSamples(float (*) [2], int, int) ()
#2  0x000000000040f787 in Spectrogram::getLine(float*, long) ()
#3  0x000000000040f621 in Spectrogram::getFFTTile(long) ()
#4  0x000000000040f301 in Spectrogram::getPixmapTile(long) ()
#5  0x000000000040f0ea in Spectrogram::paintEvent(QPaintEvent*) ()
```

1073 seconds at 2 Msps and 8 byte per sample equal roughly 15.99 GiB, so I guess there is some limit at the 16 GiB mark.

**Comment by schneider42** [comment]
Update:
compiled with -g the backrace looks like this:
```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
#1  0x000000000040eab6 in InputSource::getSamples (this=0x81ed10, dest=0x7fffffff98e0, start=-1871380480, length=1024)
    at /home/schneider/sdr/inspectrum/inputsource.cpp:37
#2  0x000000000040f787 in Spectrogram::getLine (this=0x7fffffffd6b0, dest=0x2a76230, sample=-1871380480)
    at /home/schneider/sdr/inspectrum/spectrogram.cpp:133
#3  0x000000000040f621 in Spectrogram::getFFTTile (this=0x7fffffffd6b0, tile=-1871380480) at /home/schneider/sdr/inspectrum/spectrogram.cpp:121
#4  0x000000000040f301 in Spectrogram::getPixmapTile (this=0x7fffffffd6b0, tile=-1871380480) at /home/schneider/sdr/inspectrum/spectrogram.cpp:93
#5  0x000000000040f0ea in Spectrogram::paintEvent (this=0x7fffffffd6b0, event=0x7fffffffc220) at /home/schneider/sdr/inspectrum/spectrogram.cpp:75
#6  0x00007ffff76ebddc in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
```
